<a href="https://colab.research.google.com/github/akbota-cpu/BigData/blob/main/BD_PW_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

np.random.seed(42)
n = 1_000_000

data = np.column_stack([
    np.arange(1, n + 1),
    np.random.randint(1, 1001, n),
    np.random.randint(500, 100000, n),
    np.random.randint(1, 10, n),
    np.random.randint(1, 6, n)
])

print("Размер:", data.shape)

Размер: (1000000, 5)


In [5]:
print("Количество записей:", data.shape[0])
print("Количество столбцов:", data.shape[1])

# Первые 10 записей
print(data[:10])

# Последние 10 записей
print(data[-10:])

Количество записей: 1000000
Количество столбцов: 5
[[    1   103 67621     8     4]
 [    2   436 19204     5     3]
 [    3   861 78245     9     5]
 [    4   271 28269     3     2]
 [    5   107 93611     7     1]
 [    6    72 62202     1     1]
 [    7   701 32758     6     1]
 [    8    21  2105     9     5]
 [    9   615 74759     2     2]
 [   10   122  8257     4     1]]
[[ 999991     703   71732       6       5]
 [ 999992     411   24031       8       1]
 [ 999993     431   10839       5       1]
 [ 999994     123   46004       4       2]
 [ 999995     582   59805       1       4]
 [ 999996      91   73926       3       5]
 [ 999997     318    9906       5       2]
 [ 999998     479    7105       9       5]
 [ 999999      21   66427       3       3]
 [1000000     901    3007       9       2]]


In [8]:
# Выборка по диапазону индексов
selected_data=data[100000:100010]
print(selected_data)

[[100001    714  50166      8      3]
 [100002    384  92974      7      5]
 [100003    428  18938      9      4]
 [100004    158  48814      3      2]
 [100005    745  35719      3      2]
 [100006    627  22667      1      3]
 [100007    225  53019      3      1]
 [100008    557  36139      6      4]
 [100009    729  36277      5      5]
 [100010    999  32586      1      4]]


In [9]:
# Тек сатып алу сомасы мен тауар саны бағандарын бөліп алу
selected_columns = data[:, [0, 1]]
print(selected_columns)

[[      1     103]
 [      2     436]
 [      3     861]
 ...
 [ 999998     479]
 [ 999999      21]
 [1000000     901]]


In [10]:
# Әр бағанның минималды және максималды мәндерін анықтау
print("Ең аз сатып алу сомасы:", np.min(data[:, 0]))
print("Ең көп сатып алу сомасы:", np.max(data[:, 0]))

Ең аз сатып алу сомасы: 1
Ең көп сатып алу сомасы: 1000000


In [11]:
# Кез-келген бағанның орташа мәнін есептеу мысалы
average_amount = np.mean(data[:, 0])
print("Орташа сатып алу сомасы:", average_amount)

Орташа сатып алу сомасы: 500000.5


In [12]:
# Слайсингтің жазылу форматы
# array[start:stop:step]
#start - бөліп алуды бастайтын индекс;
#stop - бөліп алуды тоқтататын индекс (бұл индекс нәтижеге кірмейді);
#step - индекстер арасындағы қадам.

import numpy as np
data = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(data[2:6])


[30 40 50 60]


In [14]:
import numpy as np

np.random.seed(42)
n = 1_000_000
#бір өлшемді массивті бағандар ретінде біріктіріп, екі өлшемді массив жасайды
data = np.column_stack([
    np.arange(1, n + 1),
    np.random.randint(1, 1001, n),
    np.random.randint(500, 100000, n),
    np.random.randint(1, 10, n),
    np.random.randint(1, 6, n)
])

# 1. Алғашқы 1000 жазбаны алыңыз
first_1000 = data[:1000]
print("Алғашқы 1000 жазба, өлшемі:", first_1000.shape)

# 2. Әр 10-жазбаны таңдаңыз (шаг 10)
every_10th = data[::10]
print("Әр 10-жазба, өлшемі:", every_10th.shape)

# 3. Соңғы 5000 жазбаны бөліп алыңыз
last_5000 = data[-5000:]
print("Соңғы 5000 жазба, өлшемі:", last_5000.shape)

# 4. 2–5 бағандарды таңдаңыз (индекстер 2:5, яғни 3-ші, 4-ші, 5-ші бағандар)
columns_2_5 = data[:, 2:5]
print("2-5 бағандар, өлшемі:", columns_2_5.shape)

# 5. Тек баға, жеңілдік, салық бағандарын бір массивке жинақтау
price_discount_tax = data[:, [2, 3, 4]]
print("Баға, жеңілдік, салық бағандары, өлшемі:", price_discount_tax.shape)

# 6. 100000–200000 аралығындағы жазбалардан бөлек деректер жиынын құру
subset_100000_200000 = data[100000:200000]
print("100000-200000 аралығы, өлшемі:", subset_100000_200000.shape)

Алғашқы 1000 жазба, өлшемі: (1000, 5)
Әр 10-жазба, өлшемі: (100000, 5)
Соңғы 5000 жазба, өлшемі: (5000, 5)
2-5 бағандар, өлшемі: (1000000, 3)
Баға, жеңілдік, салық бағандары, өлшемі: (1000000, 3)
100000-200000 аралығы, өлшемі: (100000, 5)


In [15]:
import numpy as np
# Сатып алу сомалары
data = np.array([
    5000, 7000, 8000, 6000, 9000,
    7500, 8500, 6500, 10000, 500000
])
# Орташа мән
mean = np.mean(data)
# Стандартты ауытқу
std = np.std(data)
# Z-score есептеу
z_scores = (data - mean) / std
# Аномалияларды анықтау
anomalies = data[np.abs(z_scores) > 2]
print("Орташа мән:", mean)
print("Z-score:", z_scores)
print("Аномалиялар:", anomalies)


Орташа мән: 56750.0
Z-score: [-0.35023816 -0.33670239 -0.3299345  -0.34347028 -0.32316662 -0.33331845
 -0.32655056 -0.34008633 -0.31639873  2.99986602]
Аномалиялар: [500000]


In [16]:
anomalies = data[np.abs(z_scores) > 2]
print("Анықталған аномалиялар:", anomalies)

Анықталған аномалиялар: [500000]


In [17]:
indisec = np.where(np.abs(z_scores) > 2)[0]
print("Аномалия индексі:", indisec)
print("Аномалия мәндері:", data[indisec])

Аномалия индексі: [9]
Аномалия мәндері: [500000]


In [18]:
# Аномалияларды алып тастау
clean_data = data[np.abs(z_scores) <= 2]

# Жаңа орташа мән
new_mean = np.mean(clean_data)

print("Бастапқы орташа мән:", np.mean(data))
print("Аномалиясыз орташа мән:", new_mean)

Бастапқы орташа мән: 56750.0
Аномалиясыз орташа мән: 7500.0


In [19]:
print("Аномалияға дейінгі орташа мән:", np.mean(data))
print("Аномалиядан кейінгі орташа мән:", np.mean(clean_data))

Аномалияға дейінгі орташа мән: 56750.0
Аномалиядан кейінгі орташа мән: 7500.0


In [20]:
import numpy as np

data = np.array([
    [
        [100, 200, 300],
        [400, 500, 600]
    ],
    [
        [700, 800, 900],
        [1000, 1100, 1200]
    ]
])

print(data)

[[[ 100  200  300]
  [ 400  500  600]]

 [[ 700  800  900]
  [1000 1100 1200]]]


In [21]:
print(data.shape)

(2, 2, 3)


In [28]:
import numpy as np

np.random.seed(42)
sales = np.random.randint(
    1000,
    50000,
    size=(4, 12, 30)
)
print("Массивтің өлшемі:", sales.shape)

# 1. Бірінші аймақтың барлық деректерін алыңыз
region1 = sales[0]
print("Бірінші аймақтың деректері:\n", region1)


Массивтің өлшемі: (4, 12, 30)
Бірінші аймақтың деректері:
 [[16795  1860 39158 45732 12284  7265 17850 38194 22962 48191 45131 17023
  42090  2685  1769  3433  6311 38819 40188 18568 20769 29693  7396 28480
  42434 26658 19942 19431  3747  1189]
 [20118 36773  2899  2267 32551 12394  4556  4890 42606 31740 15502 22777
  11627  9792 44323 44021  9433 44001 12016 24897  3612 24483 49555 18159
  45974 41994 15541 36920 27531  2585]
 [ 4943 24939 20457  2021 12653 44573 14417 41757 10692 46758  7873  6675
   1161 38065 27557 34763 33606 12534 30127 41397 26851  2016 25253 25276
  24247 25300  9529 18262 10268 22271]
 [13185 22243 40099  9571 40976 39044 49984 41774  3568  3027  3695 49190
   6258 23002 40504 34159 14986 13666 39660  4561 27854 39952 23662  9392
  31535 14067 49033 24599 36222 12837]
 [15039 31818 20115 11965 25538 43530  6056 33482 48716  9110 14773 28266
  18412 34270  7910 46453 26446  1206 22518 23361 24419 49702 42523 46151
  23403 19141 15820 41342  7374  2678]
 [3482

In [27]:
# 2. Үшінші аймақтың 5-айдағы барлық күндік сатылымдарын алыңыз
region3_month5 = sales[2, 4]
print("Үшінші аймақтың 5-айдағы сатылымдары:\n", region3_month5)

Үшінші аймақтың 5-айдағы сатылымдары:
 [14051 40649  7949 43289  9017  7941 26934 24386 11209 18715 29920 32703
 43318  5637  5854 44088 38660 40811 20856 22833 20963 37932 28169  8941
 15388  6569  5300 40037 37586 13015]


In [26]:
# 3. Барлық аймақтардың бірінші айдағы сатылымдарын алыңыз
month1_all_regions = sales[:, 0, :]
print("Барлық аймақтардың бірінші айдағы сатылымдары:\n", month1_all_regions)

Барлық аймақтардың бірінші айдағы сатылымдары:
 [[16795  1860 39158 45732 12284  7265 17850 38194 22962 48191 45131 17023
  42090  2685  1769  3433  6311 38819 40188 18568 20769 29693  7396 28480
  42434 26658 19942 19431  3747  1189]
 [46236  1699  1190 11492 36743  7102 20778 27641 35584 33745 24093  1569
  39210 35663 37631 46681  8455  5014 12093 19070 36777 17538 11729 35177
  46017  1784 28751 41864 41328 13533]
 [39413 43356 45597 41821  4330 20087 42430 25504  8114 14323 35121 11975
  12023 22447 25933 24959  1667 30703 10337 47427 37487 20129 41251 32921
  34307 28355 38732  5835 21159 39810]
 [44925  6951 22852  9007 42832 31523 24325 22204 16524 20282 24930  1077
  41345 21611 17984 15060 18449 19520 44303 10510 30287 29173 40711 12954
   8804  7565  6984 22526 38438 19574]]


In [29]:
# 4. Бірінші және екінші аймақтардың деректерін бөліп алыңыз
region1_2 = sales[0:2]
print("Бірінші және екінші аймақтардың деректері (өлшемі):", region1_2.shape)


Бірінші және екінші аймақтардың деректері (өлшемі): (2, 12, 30)


In [30]:
# 5. Әр аймақ бойынша жылдық сатылым көлемін есептеңіз
yearly_sales_per_region = sales.sum(axis=(1, 2))
print("Әр аймақтың жылдық сатылым көлемі:", yearly_sales_per_region)

Әр аймақтың жылдық сатылым көлемі: [8988437 9002738 8933733 9099783]


In [31]:
# 6. Әр ай бойынша барлық аймақтардың сатылымын есептеңіз
monthly_sales_all_regions = sales.sum(axis=(0, 2))
print("Әр ай бойынша барлық аймақтардың сатылымы:", monthly_sales_all_regions)

Әр ай бойынша барлық аймақтардың сатылымы: [2873017 2748877 2903471 3054682 3081950 3046742 2869644 3364570 2738741
 2997511 3227048 3118438]


In [32]:
# 7. Әр аймақтың ең жоғары күндік сатылымын анықтаңыз
max_daily_sales_per_region = sales.max(axis=(1, 2))
print(" Әр аймақтың ең жоғары күндік сатылымы:", max_daily_sales_per_region)

 Әр аймақтың ең жоғары күндік сатылымы: [49984 49816 49513 49854]


In [33]:
# 8. Әр аймақтың ең төменгі күндік сатылымын анықтаңыз
min_daily_sales_per_region = sales.min(axis=(1, 2))
print("Әр аймақтың ең төменгі күндік сатылымы:", min_daily_sales_per_region)

Әр аймақтың ең төменгі күндік сатылымы: [1161 1190 1009 1077]


In [34]:
import numpy as np

np.random.seed(42)
n = 1_000_000

# 1-КЕЗЕҢ. ДЕРЕКТЕРДІ ҚАЛЫПТАСТЫРУ

customer_id = np.random.randint(1, 50001, n).astype(float)      # Клиент ID
product_id = np.random.randint(1, 1001, n).astype(float)        # Өнім ID
purchase_amount = np.random.uniform(100, 50000, n)              # Сатып алу сомасы
quantity = np.random.randint(1, 11, n).astype(float)            # Тауар саны
discount = np.random.uniform(0, 0.5, n)                         # Жеңілдік мөлшері (0-50%)
region_code = np.random.randint(1, 6, n).astype(float)          # Аймақ коды (1-5)

data = np.column_stack([
    customer_id, product_id, purchase_amount, quantity, discount, region_code
])

columns = ["customer_id", "product_id", "purchase_amount", "quantity", "discount", "region_code"]

print("Массивтің өлшемі:", data.shape)
print("Массивтің dtype:", data.dtype)

Массивтің өлшемі: (1000000, 6)
Массивтің dtype: float64


In [35]:
# АҚАУЛАРДЫ ЖАСАНДЫ ЕНГІЗУ

# Қайталанатын жазбалар
dup_idx = np.random.choice(n, 5000, replace=False)
data = np.vstack([data, data[dup_idx]])

# Жетіспейтін мәндер (purchase_amount бағанына NaN)
nan_idx = np.random.choice(data.shape[0], 3000, replace=False)
data[nan_idx, 2] = np.nan

# Аномалиялар (шектен тыс үлкен сома)
outlier_idx = np.random.choice(data.shape[0], 500, replace=False)
data[outlier_idx, 2] = np.random.uniform(500000, 2000000, 500)


# 2-КЕЗЕҢ. ДЕРЕКТЕРДІ ТЕКСЕРУ

unique_rows, counts = np.unique(data, axis=0, return_counts=True)
print("Артық (қайталанған) жолдар саны:", data.shape[0] - unique_rows.shape[0])

missing_mask = np.isnan(data[:, 2])
print("Жетіспейтін мәндер саны:", missing_mask.sum())

valid_amounts = data[~missing_mask, 2]
mean_amt = np.mean(valid_amounts)
std_amt = np.std(valid_amounts)
z_scores = np.abs((data[:, 2] - mean_amt) / std_amt)
outlier_mask = z_scores > 3
print("Аномалиялар саны (z-score > 3):", np.nansum(outlier_mask))


# 3-КЕЗЕҢ. ДЕРЕКТЕРДІ ӨҢДЕУ

median_amt = np.nanmedian(data[:, 2])
data[missing_mask, 2] = median_amt                 # жетіспейтін мәндерді толтыру

data_unique = np.unique(data, axis=0)               # қайталануларды жою

z_scores_clean = np.abs((data_unique[:, 2] - np.mean(data_unique[:, 2])) / np.std(data_unique[:, 2]))
clean_data = data_unique[z_scores_clean <= 3]        # аномалияларды жою

selected_columns = clean_data[:, [0, 2, 5]]          # қажетті бағандарды бөліп алу
filtered = clean_data[clean_data[:, 2] > 10000]      # шарт бойынша фильтр


# 4-КЕЗЕҢ. МАТЕМАТИКАЛЫҚ ЕСЕПТЕУЛЕР

total_revenue = np.sum(clean_data[:, 2])
print("Жалпы табыс:", round(total_revenue, 2))

region_sales = {}
for region in np.unique(clean_data[:, 5]):
    region_sales[int(region)] = np.sum(clean_data[clean_data[:, 5] == region, 2])
print("Әр аймақтың жалпы сатылымы:", region_sales)


# 5-КЕЗЕҢ. СТАТИСТИКАЛЫҚ ТАЛДАУ

amounts = clean_data[:, 2]
print("Орташа мән:", round(np.mean(amounts), 2))
print("Медиана:", round(np.median(amounts), 2))
print("Минимум:", round(np.min(amounts), 2))
print("Максимум:", round(np.max(amounts), 2))
print("Стандартты ауытқу:", round(np.std(amounts), 2))
print("Q1:", round(np.percentile(amounts, 25), 2))
print("Q3:", round(np.percentile(amounts, 75), 2))

Артық (қайталанған) жолдар саны: 4968
Жетіспейтін мәндер саны: 2999
Аномалиялар саны (z-score > 3): 500
Жалпы табыс: 25019097949.05
Әр аймақтың жалпы сатылымы: {1: np.float64(4975740572.765188), 2: np.float64(5003678738.531414), 3: np.float64(4998319282.56654), 4: np.float64(5007055659.54895), 5: np.float64(5034303695.639139)}
Орташа мән: 25030.81
Медиана: 25032.51
Минимум: 100.07
Максимум: 49999.97
Стандартты ауытқу: 14379.63
Q1: 12611.82
Q3: 37460.06
